### ISSUE TITLE
plugin fails when SAP JVM is used

### ISSUE THREAD

**Issue by martin-moser** [SAP/cf-cli-java-plugin#11]
Hi Michele,

Unfortunately, there plugin fails for apps that use the SAP JVM: the commands jmap and jstack are not available.

Best,

Martin

**Comment by michele-mancioppi** [comment]
Mmm, then the plugin won't work on the SAP Java Buildpack. I think, however, that the XS colleagues have the functionality in the `xs java` command.

@ScheererJ, can you share with Martin a link to the `xs java` docu?

**Comment by ScheererJ** [comment]
You can find the official documentation of `xs java` [here](https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.02/en-US/8bb90c8be912431dab74877a492a3f5a.html#loio8bb90c8be912431dab74877a492a3f5a__section_ojd_gjh_1z).
