### ISSUE TITLE
Support SAP Java buildpack

### ISSUE THREAD

**Issue by michele-mancioppi** [SAP/cf-cli-java-plugin#12]
Enable plugin to work with `jvmmon` instead of `jmap` and `jstack` so that the SAP Java Buildpack in default configuration (JRE inside) is supported.

**Comment by michele-mancioppi** [comment]
Also, consider using `jcommand` so that the SAP Machine is supported as well.

**Comment by TimGerlach** [comment]
Actually, we should not only _consider_ using `jcmd` but migrate the plugin from `jmap` to `jcmd` as `jmap` becomes deprecated from Java 10.

**Comment by michele-mancioppi** [comment]
Yeah, pretty much `jcmd` is a must. And we might more easily add things like support for class histograms and recordings. AFAIK `jcmd` is 7+ and shipped with JREs, so we do not really drop any compatibility.

**Comment by TimGerlach** [comment]
Great! Let's plan it into one of the next sprints.

**Comment by michele-mancioppi** [comment]
Actually Johannes volunteered to implement this one :D
