### ISSUE TITLE
unknown error occured while checking existence of required tools jvmmon/jmap

### ISSUE THREAD

**Issue by Ghenty** [SAP/cf-cli-java-plugin#29]
Hi,

can anyone tell me what I am doing wrong here?
cf java heap-dump xsuaa-provisioning --local-dir ./ --app-instance-index 2
ends up in:
FAILED
unknown error occured while checking existence of required tools jvmmon/jmap

Best regards,
Christian

**Comment by rampandu69701** [comment]
Hi,
I am also facing the same issue with cf cli v7. Any plans for fixing the issue?

Thanks,
Ram

**Comment by TimGerlach** [comment]
Just talked to @rampandu69701, adding the JDK explicitly solved this issue:
```yaml
JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { repository_root: "[https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64"](https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64%22), version: 11.+ } }'
```

Feel free to reopen this issue if it continues to show up after adding the JDK.
