### ISSUE TITLE
Taking heap dumps: Error message is easy to miss when "jmap" command fails

### ISSUE THREAD

**Issue by volpav** [SAP/cf-cli-java-plugin#9]
Hey folks -

We've ran into an interesting issue with `heap-dump` command the other day. Basically, we were executing something like the following: 

    cf java heap-dump my-app > dump-file.bin

Even though the output file was around 70MB, we couldn't open it (read error). We've tried the same command on other apps deployed into the same CF space and they went through just fine.

We've later discovered (with the help from `dry-run`) that the `jmap` command was failing with an error (not enough container disk space to store the entire file) but since we were piping everything and because some of the data from the heap was still being written to disk (again, around 70MB before there was no more space left on the device), we couldn't see what was going on, ending up with invalid dump.

The idea for the fix that I have is to check `stderr` after executing `jmap` command and if there was something written to it, print it and abort. I came-up with the following wrapper:

    err=$(%s 2>&1 > /dev/null); if [ ! -z \"$err\" ]; then echo $err; exit 1; else %s; fi

The first parameter is the current `jmap` command whereas the second parameter is the current `cat` command.

Let me know if I can submit a PR.

Cheers,

Pavel.

**Comment by michele-mancioppi** [comment]
Please do submit :-) We could also add a check for the execution status of the last command, and then check the 'stderr', I think it would be more resilient.

**Comment by michele-mancioppi** [comment]
Of course, please make sure to follow the steps outlined in https://github.com/SAP/cf-cli-java-plugin/blob/master/CONTRIBUTING.md :-)

**Comment by michele-mancioppi** [comment]
I played around with possible error scenarios and I found also issues when the heap dump file already exists (which could happen when one if copying and pasting the dry-run output :D).

Thanks @volpav for the great input!
